import fs from "node:fs";
import { detectCat } from "/home/user/Cat-Intelligence-Agency/bots/lib/catdetect.mjs";
const V = JSON.parse(fs.readFileSync(new URL("./verified.json", import.meta.url)));
const C = JSON.parse(fs.readFileSync(new URL("./census.json", import.meta.url)));
const ch = new Map(JSON.parse(fs.readFileSync(new URL("./chainread.json", import.meta.url))).rows.map(r => [r.mint, r]));
const TOKEN="TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", T22="TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
console.log("verified list", V.length, "isVerified true", V.filter(t=>t.isVerified===true).length);
const cats = V.filter(t => detectCat({ name: t.name, symbol: t.symbol }).isCat);
console.log("cats in verified list", cats.length);
const vol = t => t.stats24h ? (t.stats24h.buyVolume ?? 0) + (t.stats24h.sellVolume ?? 0) : null;
const now = Date.parse("2026-09-25T10:21:52Z");
const ageD = t => t.firstPool?.createdAt ? (now - Date.parse(t.firstPool.createdAt))/864e5 : null;
const q = (arr, p) => { const s=[...arr].filter(x=>x!=null).sort((a,b)=>a-b); return s.length? s[Math.floor(p*(s.length-1))]:null; };
console.log("program", cats.reduce((m,t)=>(m[t.tokenProgram===TOKEN?"spl":t.tokenProgram===T22?"t22":t.tokenProgram]=(m[t.tokenProgram===TOKEN?"spl":t.tokenProgram===T22?"t22":t.tokenProgram]||0)+1,m),{}));
console.log("audit mint disabled", cats.filter(t=>t.audit?.mintAuthorityDisabled===true).length, "freeze disabled", cats.filter(t=>t.audit?.freezeAuthorityDisabled===true).length, "both", cats.filter(t=>t.audit?.mintAuthorityDisabled===true&&t.audit?.freezeAuthorityDisabled===true).length, "audit missing mint flag", cats.filter(t=>t.audit?.mintAuthorityDisabled==null).length, "missing freeze flag", cats.filter(t=>t.audit?.freezeAuthorityDisabled==null).length);
console.log("liquidity quantiles", [0.1,0.25,0.5,0.75,0.9].map(p=>Math.round(q(cats.map(t=>t.liquidity),p))));
console.log("organic quantiles", [0.1,0.25,0.5,0.75,0.9].map(p=>q(cats.map(t=>t.organicScore),p)?.toFixed(1)), "missing", cats.filter(t=>t.organicScore==null).length);
console.log("age days quantiles", [0.05,0.1,0.25,0.5].map(p=>q(cats.map(ageD),p)?.toFixed(1)), "missing", cats.filter(t=>ageD(t)==null).length);
console.log("holders quantiles", [0.1,0.25,0.5].map(p=>q(cats.map(t=>t.holderCount),p)), "missing", cats.filter(t=>t.holderCount==null).length);
console.log("topHolders quantiles", [0.5,0.75,0.9].map(p=>q(cats.map(t=>t.audit?.topHoldersPercentage),p)?.toFixed(1)), "missing", cats.filter(t=>t.audit?.topHoldersPercentage==null).length);
console.log("vol quantiles", [0.25,0.5,0.75].map(p=>Math.round(q(cats.map(vol),p))));
// funnel
let s = cats; const step=(label,f)=>{const before=s.length; s=s.filter(f); console.log(label.padEnd(50), before, "->", s.length);};
step("classic SPL program (Jupiter's word)", t=>t.tokenProgram===TOKEN);
step("mint auth disabled (Jupiter audit)", t=>t.audit?.mintAuthorityDisabled===true);
step("freeze auth disabled (Jupiter audit)", t=>t.audit?.freezeAuthorityDisabled===true);
step("liq >= 25k", t=>(t.liquidity??0)>=25000);
step("vol24h >= 1k (measured, not null)", t=>(vol(t)??0)>=1000);
step("age >= 30d", t=>ageD(t)!=null && ageD(t)>=30);
console.log(s.map(t=>`${t.symbol} liq ${Math.round(t.liquidity)} vol ${Math.round(vol(t))} org ${t.organicScore?.toFixed?.(0)} age ${ageD(t)?.toFixed(0)} top ${t.audit?.topHoldersPercentage?.toFixed?.(1)} hold ${t.holderCount}`).join("\n"));
