// The final 24, in sheet order. `body` is the story; the description is body + " " + disclosure.
// `changed` lists what the editor changed from the checker's pick.
export const COINS = [
  { pair: "SPYx", name: "Patchpaw the Calico", ticker: "PATCHPAW",
    body: "Patchpaw is a little calico whose coat is a quilt of many small patches, no two alike. She pads through every flower bed in the garden and sniffs each one.",
    disc: "A cat coin priced in SPYx. Not affiliated with State Street or StonkFun. No intrinsic value; not financial advice.",
    look: "A small, normal four-legged calico house cat. Her coat is a patchwork of many small patches in orange, black, white, grey and cream, like a quilt. One front paw is all white, and she has bright green eyes. She wears nothing: no collar, no logo, no emblem of any kind.",
    changed: ["look only: 'no spider, no ship' -> 'no emblem of any kind' (naming the issuer's spider in a picture prompt invites the generator to draw one; checkTerms flagged 'spider')"] },
  { pair: "QQQx", name: "Hundred Whisker Cat", ticker: "WHISK100",
    body: "A fluffy chocolate-brown cat with a hundred white whiskers, one for each name in its basket. Each morning it tries to count them and loses track at forty.",
    disc: "A cat coin priced in QQQx. Not affiliated with Invesco, Nasdaq or StonkFun. No intrinsic value; not financial advice.",
    look: "A fluffy long-haired house cat with a rich, solid chocolate-brown coat, a white chest and bright green eyes. It has very long, bright white whiskers that fan out wide on both sides of its face and stand out against the dark fur. A normal four-legged house cat that wears nothing.",
    changed: ["coat silver-grey -> chocolate-brown (too many grey cats; Harrumph is also a fluffy grey long-hair)", "story: 'cat said to have' -> 'cat with' (the repo's matcher compacts 'cat s...' into the SPCXx mascot 'Cat 5')"] },
  { pair: "GLDx", name: "Ingot the Loaf Cat", ticker: "INGOTLOAF",
    body: "Ingot, a sleek honey-golden cat, tucks in her paws and loafs on the warm garden steps, shaped just like a little bar.",
    disc: "A cat coin priced in GLDx. Not affiliated with SPDR Gold Trust, State Street, World Gold Council or StonkFun. No intrinsic value; not financial advice.",
    look: "An ordinary four-legged house cat with a sleek, short, honey-golden coat, a soft metallic sheen and warm orange eyes. It likes to sit in a neat 'cat loaf' pose with its paws tucked under, so its body looks like a small rounded ingot. It wears nothing; no logos or text.",
    changed: ["look only: 'small rounded gold bar' -> 'small rounded ingot' ('GOLD' is the pair's own StonkFun name)"] },
  { pair: "TSLAx", name: "Snowcurl the Shade Cat", ticker: "SNOWCURL",
    body: "Snowcurl is a sleek white cat with her tail held high and curled at the tip. On hot days she finds cool shade, lifts a paw to wash her face and waits calmly.",
    disc: "A cat coin priced in TSLAx. Not affiliated with Tesla, Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A sleek, glossy, solid-white short-haired house cat on four legs, standing in cool garden shade. Its tail is held straight up and curls over at the tip, and one front paw is lifted to its face as if washing. It wears nothing: no collar, badge or logo.",
    changed: ["name 'Snowcurl the Garden Cat' -> 'Snowcurl the Shade Cat' (three picks were '... the Garden Cat')"] },
  { pair: "NVDAx", name: "Sockfoot the Morning Cat", ticker: "SOCKFOOT",
    body: "Sockfoot is a grey tabby with a white bib and four white paws like socks. At first light he walks the edge of the lawn, tail held high, the first cat up.",
    disc: "A cat coin priced in NVDAx. Not affiliated with NVIDIA Corporation or StonkFun. No intrinsic value; not financial advice.",
    look: "A slim dark-grey tabby shorthair house cat with a white chin and muzzle, a white bib and four white paws that look like socks, and a long striped grey tail held up, walking along a garden path beside the lawn at first light. It wears nothing; the 'socks' are only its white fur.",
    changed: ["name 'Sockfoot the Garden Tabby' -> 'Sockfoot the Morning Cat'", "story ending 'sniffs the flowers, then naps on warm stones' -> 'tail held high, the first cat up' (Patchpaw sniffs the flower beds; Save Point napped on a warm stone)"] },
  { pair: "AAPLx", name: "Rosette the Climbing Cat", ticker: "ROSETTE",
    body: "Rosette is a stocky golden-tan cat dappled with black rosette spots. She climbs the old oak by the lawn and dozes along a low branch, one paw dangling.",
    disc: "A cat coin priced in AAPLx. Not affiliated with Apple Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A stocky, muscular short-haired house cat with a golden-tan coat covered in black ring-shaped rosette spots. It has a pale cream belly and chin, a thick tail, round golden eyes and nothing worn. It lies stretched along a low oak branch with one front paw dangling.",
    changed: ["name 'Rosette the Garden Cat' -> 'Rosette the Climbing Cat'", "story: pond and 'flops in the sun' -> climbs the old oak and dozes on a branch (Moat Cat owns the pond; Milkweed flops in the sun)", "look: 'round amber eyes' -> 'round golden eyes' (checkFields reads 'amber eyes' as a person's name, real_person)"] },
  { pair: "MSFTx", name: "Halfsmile Cat", ticker: "HALFSMILE",
    body: "A grey-and-white cat with grey-green eyes and a crooked grin that looks cross until you see she is pleased. She grins at all who pass her garden bench.",
    disc: "A cat coin priced in MSFTx. Not affiliated with Microsoft Corporation or StonkFun. No intrinsic value; not financial advice.",
    look: "A normal four-legged grey-and-white house cat with grey-green eyes and a crooked grin, one corner of its mouth tucked up, sitting upright on a wooden garden bench. No collar and no accessories.",
    changed: ["story: 'Loves laps, slow blinks and loud purrs' -> sits on the garden bench and grins at passers-by (Harrumph climbs into laps; Porchlight slow-blinks)", "'half-smile' in story and look -> 'crooked grin' (the simulated AMZNx row lists the brand 'Smile')"] },
  { pair: "GOOGLx", name: "Porchlight the Dusk Cat", ticker: "PORCHLIGHT",
    body: "Porchlight is a solid black cat with a shiny coat and bright yellow eyes. When the garden lanterns glow, she sits on the porch step and slowly blinks hello.",
    disc: "A cat coin priced in GOOGLx. Not affiliated with Alphabet Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A normal four-legged house cat with a shiny, solid black coat and yellow eyes. No markings, clothes or accessories. She sits on a porch step lit by warm garden lanterns at dusk.",
    changed: [] },
  { pair: "AMZNx", name: "Sunmane the Sundial Cat", ticker: "SUNMANE",
    body: "Sunmane, a sturdy tawny cat with a fluffy ruff like a little mane, sits on the old sundial all day and turns slowly to follow the sun.",
    disc: "A cat coin priced in AMZNx. Not affiliated with Amazon or StonkFun. No intrinsic value; not financial advice.",
    look: "A sturdy, broad-faced short-haired house cat with a plain warm tawny (sandy golden-brown) coat and no stripes or spots, a pale cream chin and belly, and a thick fluffy ruff of slightly darker tawny fur around the neck. Warm golden eyes, calm and proud. He sits upright on top of an old stone sundial, an ordinary four-legged house cat. He wears nothing. There is no film-strip ring, ribbon, open-mouthed pose, text or logo.",
    changed: ["name 'Sunmane the Garden Cat' -> 'Sunmane the Sundial Cat'", "story: 'naps in the warmest patch ... pads his rounds at dusk' -> sits on the old sundial and follows the sun (four other picks napped in a warm spot)", "look: 'Amber eyes' -> 'Warm golden eyes' (real_person 'amber eyes'); 'roar pose' -> 'open-mouthed pose' (own-stock term 'roar'); 'cat sitting' rephrased (compacts to 'Cat 5')"] },
  { pair: "METAx", name: "Couch Captain Cat", ticker: "COUCHCAP",
    body: "A fluffy brown tabby with golden eyes who claims the sofa every evening, remote in paw, picks the show for the whole house and naps before the ending.",
    disc: "A cat coin priced in METAx. Not affiliated with Meta Platforms, Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A fluffy, medium-long-haired brown tabby cat with a white chest and muzzle, golden-yellow eyes and tufted ears. It sits upright on a grey sofa with one front paw on a small dark TV remote, like a captain at the helm. No logos, watermark or text.",
    changed: [] },
  { pair: "COINx", name: "Harrumph the Pouty Cat", ticker: "HARRUMPH",
    body: "Harrumph, a fluffy grey long-haired cat with a flat face and a grumpy pout, glares at pigeons from the garden wall all morning, then climbs into a lap to purr.",
    disc: "A cat coin priced in COINx. Not affiliated with Coinbase or StonkFun. No intrinsic value; not financial advice.",
    look: "A fluffy, flat-faced long-haired house cat in a soft smoky grey-taupe coat, with blue-green eyes, a grumpy downturned pout, small tufted ears and slightly darker grey paws. It wears nothing.",
    changed: ["look only: dropped 'just like the original' (an artist reading the look cannot know which original)"] },
  { pair: "HOODx", name: "Pewter the Catmint Cat", ticker: "PEWTER",
    body: "Pewter, a silver-grey tabby with dark stripes on her cheeks, a white chin and a pink nose, rolls in the catmint patch each afternoon until she is happily dizzy.",
    disc: "A cat coin priced in HOODx. Not affiliated with Robinhood or StonkFun. No intrinsic value; not financial advice.",
    look: "A normal four-legged house cat with a light silver-grey tabby coat: darker grey stripes across the cheeks, with softer tabby striping on the head and back, a white muzzle and chin, a pink nose, pink inner ears and grey paws. She lies on her side in a patch of flowering catmint, paws curled and eyes half-closed, content. She wears nothing: no hat and no clothing.",
    changed: ["name 'Pewter the Garden Tabby' -> 'Pewter the Catmint Cat'", "story: 'naps on the warm garden steps' -> rolls in the catmint (Ingot already loafs on the warm garden steps)"] },
  { pair: "MSTRx", name: "Trinket the Tortie Cat", ticker: "TRINKETCAT",
    body: "Trinket, a round fluffy tortoiseshell, adds one shiny pebble a day to her secret pile behind the rain barrel and has never given one back.",
    disc: "A cat coin priced in MSTRx. Not affiliated with Strategy Inc. (MicroStrategy) or StonkFun. No intrinsic value; not financial advice.",
    look: "A round, fluffy tortoiseshell house cat (mottled black fur with warm amber and cream patches, green eyes) sitting proudly on a small heap of plain smooth shiny pebbles beside a wooden rain barrel. The pebbles are blank, with no markings, symbols or letters, and the cat wears nothing.",
    changed: ["pile moved from 'under the garden shed' to 'behind the rain barrel' (Latchkey's strongbox is in the shed)", "look: 'no coins' -> 'no markings' (COIN is COINx's root)"] },
  { pair: "CRCLx", name: "Tuppence the Tweed Cat", ticker: "TUPPENCE",
    body: "Tuppence, a tubby blue-grey cat in a flat tweed cap, waddles to the garden tea table at four o'clock sharp and waits politely for crumbs.",
    disc: "A cat coin priced in CRCLx. Not affiliated with Circle or StonkFun. No intrinsic value; not financial advice.",
    look: "A tubby, round-bellied short-haired house cat with a plush, solid blue-grey coat and round copper eyes. It wears a small flat brown tweed cap. It is an ordinary four-legged house cat, waiting politely beside a little garden tea table.",
    changed: ["coat silver tabby -> solid blue-grey with copper eyes (the coat was made up; five picks were silver or grey tabbies)", "story: path stroll and bees -> tea-table crumbs (Sockfoot walks the path; Rosette watched the bees)", "look: 'cat, sitting' rephrased (compacts to the SPCXx mascot term 'Cat 5')"] },
  { pair: "SPCXx", name: "Warmspot the Tuxedo Cat", ticker: "WARMSPOT",
    body: "Warmspot, a black-and-white tuxedo cat with a white stripe down her nose and a white chin, always finds the one warm spot in a snowy garden, and keeps it.",
    disc: "A cat coin priced in SPCXx. Not affiliated with SpaceX or StonkFun. No intrinsic value; not financial advice.",
    look: "A short-haired black-and-white tuxedo cat: a black mask split by a white stripe down the nose, white muzzle, chin and chest, a pink nose and pale eyes. She is curled snugly, on her own, on a warm, plain unmarked round white dish (no logo, no lettering) in the snow. Nothing worn. Always a normal four-legged house cat.",
    changed: [] },
  { pair: "PLTRx", name: "Skein the Yarn Kitten", ticker: "SKEINKIT",
    body: "Skein, a fluffy cream kitten with a pink nose, strings red yarn from post to post until every flower pot in the garden is tied to every other.",
    disc: "A cat coin priced in PLTRx. Not affiliated with Palantir Technologies Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A small fluffy cream-coloured kitten with a pink nose and big curious eyes, pawing at a loose ball of red yarn whose strands run between garden posts and flower pots like a web. It wears nothing.",
    changed: [] },
  { pair: "GMEx", name: "Save Point the Tabby", ticker: "SAVEPAWS",
    body: "Save Point, a small brown striped tabby with a cream chest and muzzle, taps the same flat stepping stone with a paw before every adventure, just in case.",
    disc: "A cat coin priced in GMEx. Not affiliated with GameStop or StonkFun. No intrinsic value; not financial advice.",
    look: "A small, young brown mackerel-tabby house cat (dark brown stripes on a warm brown-grey coat, striped legs and ringed tail) with a cream-white chest and muzzle, big ears and a pink nose, sitting on a flat garden stepping stone with one front paw raised to tap it. It wears nothing: nothing on its head or around its neck, no red yarn, no game controller, no power-button symbol, no logos.",
    changed: ["story and pose: 'finds the warmest stone ... naps on it until the sun moves on' -> taps the same stepping stone before every adventure (Warmspot's whole story is finding the one warm spot)", "look: 'No headband' -> 'nothing on its head or around its neck' (same guard, without the persona word)"] },
  { pair: "STRCx", name: "Everloop the Sleepy Cat", ticker: "EVERLOOP",
    body: "Everloop, a soft blue-cream cat, curls into a perfect ring with her nose tucked in her tail and naps in the garden as if the afternoon will never end.",
    disc: "A cat coin priced in STRCx. Not affiliated with Strategy Inc. or StonkFun. No intrinsic value; not financial advice.",
    look: "A soft, round-faced house cat with a blue-cream coat (dove-grey fur softly mottled with patches of pale cream), curled into a perfect closed ring on the grass, nose tucked into her tail, eyes shut, fast asleep in the sun. Normal four-legged house cat, no collar, no props.",
    changed: ["coat 'round silver tabby' -> 'soft blue-cream' (made-up coat; too many silver tabbies)", "look: 'closed circle' -> 'closed ring' (Circle is CRCLx's name)"] },
  { pair: "MCDx", name: "Milkweed the Meadow Cat", ticker: "MILKWEED",
    body: "Milkweed, a fluffy white cat with one blue eye and one green eye, pounces on drifting seed fluff in the long grass, then flops in the sun like a fallen cloud.",
    disc: "A cat coin priced in MCDx. Not affiliated with McDonald's or StonkFun. No intrinsic value; not financial advice.",
    look: "A fluffy, medium-long-haired, all-white house cat with odd eyes (one blue, one green) and a pink nose. It is crouched mid-pounce in long meadow grass, with seed fluff floating around it. It wears no bow, collar or clothes, and it has a realistic cat face and body. There are no logos and no red-and-yellow colour scheme.",
    changed: ["'one gold eye' -> 'one green eye' in story and look: the repo's stockCatRefusals refuses 'gold' in any stock cat's tagline (other_pair GOLD, GLDx's name)"] },
  { pair: "BRK.Bx", name: "Moat Cat", ticker: "MOATCAT",
    body: "A white calico with one ginger ear and one black ear. She sits by the garden pond as if it were her moat and lets nothing cross it but butterflies.",
    disc: "A cat coin priced in BRK.Bx. Not affiliated with Berkshire Hathaway or StonkFun. No intrinsic value; not financial advice.",
    look: "A slim, ordinary four-legged calico house cat, mostly white. A ginger patch covers one ear and that side of the top of her head, the other ear is black, and one front leg is black from the shoulder down. She has a pink nose and pink paw pads. She is a realistic cat, not a round plush toy. She wears nothing, has no tag or label, and sits calmly at the edge of a garden pond.",
    changed: ["look only: 'house cat. She is mostly white' -> 'house cat, mostly white' ('cat. She' compacts to 'Cat 5')"] },
  { pair: "KOx", name: "Tumble the Kitten", ticker: "TUMBLES",
    body: "Tumble is a small ginger tabby kitten with a white chin. Wherever she naps, more kittens pile in beside her until the whole garden hammock purrs.",
    disc: "A cat coin priced in KOx. Not affiliated with The Coca-Cola Company or StonkFun. No intrinsic value; not financial advice.",
    look: "A small, normal four-legged kitten with a ginger tabby coat, a white chin and ordinary upright ears, curled up asleep in a garden hammock. A few other kittens can snuggle in beside her. No clothes, no drink, no bottle or can, and no red-and-white colours.",
    changed: ["coat 'silver tabby with four white socks' -> 'ginger tabby with a white chin' (made-up coat; Sockfoot's four white paws come from its real cat)", "'flower bed' -> 'garden hammock' (Patchpaw owns the flower beds)"] },
  { pair: "INTCx", name: "Bracken the Fern Cat", ticker: "BRACKEN",
    body: "Bracken, a sturdy grey-brown striped tabby with a thick black-ringed tail, stalks moths through the ferns at dusk and has never once caught one.",
    disc: "A cat coin priced in INTCx. Not affiliated with Intel or StonkFun. No intrinsic value; not financial advice.",
    look: "A sturdy, broad-headed, normal four-legged house cat with a grey-brown striped tabby coat like a wild forest cat. It has a thick, bushy, blunt-ended tail with clear black rings and a black tip, and yellow-green eyes. It creeps low through tall garden ferns. It wears nothing.",
    changed: ["name 'Bracken the Tabby Cat' -> 'Bracken the Fern Cat' ('Save Point the Tabby' is also a Tabby name)", "story ending 'then naps on the warm garden wall' -> 'has never once caught one' (Harrumph owns the garden wall)", "look: 'amber-green eyes' -> 'yellow-green eyes' (real_person 'amber green'); 'house cat, sturdy' rephrased ('Cat 5' compaction); added 'creeps low through tall garden ferns'"] },
  { pair: "VIDAx", name: "Trillby the Chirping Cat", ticker: "TRILLBY",
    body: "Trillby, a slim cream cat with dark brown points and bright blue eyes, chirps back whenever anyone speaks and follows every chat around the garden.",
    disc: "A cat coin priced in VIDAx. Not affiliated with Vida Global or StonkFun. No intrinsic value; not financial advice.",
    look: "A slim, elegant colourpoint house cat: a pale cream body with a dark seal-brown face mask, ears, paws and tail, and bright blue eyes. Head tilted and mouth open in a friendly chirp. A normal four-legged cat that wears nothing.",
    changed: ["coat 'cream-and-ginger' -> colourpoint (cream with dark brown points, blue eyes): Siamese-type cats are the famously talkative ones, and the set had no pointed cat", "'from bench to flower bed' -> 'around the garden'"] },
  { pair: "DFDVx", name: "Latchkey the Vault Cat", ticker: "LATCHKEY",
    body: "Latchkey, a sturdy ginger-and-white cat, dozes upright on a little iron-banded strongbox in the garden shed, one paw on the old brass key.",
    disc: "A cat coin priced in DFDVx. Not affiliated with DeFi Development Corp. or StonkFun. No intrinsic value; not financial advice.",
    look: "A sturdy short-haired house cat with a ginger back, head and tail and a white chest, belly and chin, dozing upright on top of a small wooden strongbox with iron bands, eyes half-closed, one front paw resting on an old brass key. An ordinary four-legged cat wearing nothing: no collar, logo, lettering or symbols.",
    changed: ["coat 'brown mackerel tabby with four white socks' -> 'ginger-and-white' (made-up coat; three other brown tabbies and Sockfoot's socks)", "pose 'naps curled' -> 'dozes upright' (Everloop and Tumble already sleep curled)", "look: 'coin symbols' -> 'symbols' (COIN is COINx's root)"] },
];
