import { open, shot, T } from "./lib.mjs";
const { b, p } = await T("open", () => open());
const W = () => p.evaluate(() => window.__world.pause());
const frames = async (n) => { for (let i = 0; i < n; i++) { const t = Date.now(); await p.evaluate(() => { window.__world.pause(); window.__world.advance(0); }); console.log("  f", Date.now() - t); } };
const key = (k, n = 1) => p.evaluate(([k, n]) => { const c = document.getElementById("world"); for (let i = 0; i < n; i++) c.dispatchEvent(new KeyboardEvent("keydown", { key: k, bubbles: true })); }, [k, n]);
const S = (name) => T(name, () => shot(p, `cap/${name}.jpg`));
const closeAll = () => p.evaluate(() => { document.querySelectorAll("dialog[open]").forEach((d) => d.close()); });
await frames(1);
await p.evaluate(() => document.getElementById("adopt-open").click()); await p.waitForTimeout(1500);
await S("adopt-pill");
console.log("items", await p.evaluate(() => { const it = document.querySelectorAll("dialog[open] .find-item"); it[Math.min(6, it.length - 1)].click(); return it.length; })); await p.waitForTimeout(500); await W();
await frames(4);
await S("cat-card-2");
await p.evaluate(() => document.querySelector("#card .btn-adopt").click()); await p.waitForTimeout(800);
await p.evaluate(() => { const bs = [...document.querySelectorAll("#card .adopt-getstonked-go, #card a.btn-buy")]; (bs.at(-1) || document.querySelector("#card .adopt-pad-name"))?.scrollIntoView({ block: "end" }); });
await p.waitForTimeout(800);
await S("adopt-launch");
await p.keyboard.press("Escape"); await closeAll();
await p.evaluate(() => document.getElementById("hall-open").click()); await p.waitForTimeout(1500);
await S("hall-of-fame");
await p.keyboard.press("Escape"); await closeAll();
await p.evaluate(() => { window.__world.choose(null); window.__world.home(); window.__world.pause(); });
await key("ArrowLeft", 6); await key("+", 3); await key("ArrowDown", 1);
await frames(3);
await S("pond");
await b.close();
