// Editor overrides on base.json: [name, ticker, blurb, look, coat, disclosure?]. Blurb + " " + disclosure = description.
export const EDITS = {
  OPENAI: { blurb: "Parlor Puff, a fluffy taupe tabby with a snowy ruff and big dark eyes, sits so still by the flower pots that visitors take her for a painting.",
    disc: "A cat coin priced in OPENAI. Not affiliated with OpenAI, Tessera, PreStocks or StonkFun. No intrinsic value; not financial advice." },
  KALSHI: { name: "Squint the Weathervane Tabby", ticker: "SQUINTPAW",
    blurb: "Squint, a stout brown-grey tabby with a striped brow and gold eyes, frowns at the clouds by the Cat Sanctuary weathervane, weighing rain or shine.",
    look: "Based on the one real cat tied to the stock. It is a stocky, broad-chested, round-faced shorthair: a warm brown-grey (taupe) mackerel tabby with dark brown stripes and a striped M on the brow. It has light gold eyes set in a stern, narrowed frown, a cream chin and muzzle, and a pink-brown nose. It wears nothing, and it sits beside the Cat Sanctuary weathervane as a normal four-legged cat. The poster's milk bottle and bread were props, so they are left out." },
  ANDURIL: { name: "Hover the Cinnamon Cat", ticker: "HOVERPAW",
    blurb: "Hover, a lean cinnamon shorthair with a cream chin and gold eyes, leaps after the dragonflies around the birdbath and seems to hang in the air.",
    look: "A normal four-legged, lean, long-legged short-haired house cat with a solid warm cinnamon (light reddish-brown) coat, a cream chin and bright gold eyes. It wears nothing. It leaps after dragonflies around the garden birdbath.",
    coat: ["#B06A3F", "#8A4E2C", "solid", "#D8A93A"] },
  NEURALINK: { blurb: "Silk, a sleek lilac tabby with hair-thin darker pinstripes and a white chin, slips between the fence rails so neatly she never bends a leaf.",
    look: "A slim, sleek lilac tabby (a soft, pinkish dove-grey) with very fine darker lilac pinstripes, a white chin and green eyes. A normal four-legged house cat that wears nothing.",
    coat: ["#B7A7B2", "#7A6875", "tabby", "#8DBF5A"] },
  TTWO: { name: "Puzzle the Silver Cat", ticker: "PUZZLEPAW",
    blurb: "Puzzle, a light silver-grey cat with white cheek tufts and a white bib, lines up fallen petals in neat rows of three." },
  COST: { name: "Boxwood the Big Calico", ticker: "BOXWOOD",
    blurb: "Boxwood, a big broad-chested calico with cardboard-tan and black patches on white, naps on a tall stack of boxes in the garden shed.",
    look: "A normal four-legged, big, sturdy calico house cat: mostly white, with large cardboard-tan and black patches, and honey-gold eyes. It wears nothing. The look comes from the business: bulk boxed goods stacked on pallets.",
    coat: ["#F4EFE6", "#C39A6B", "calico", "#D9A03A"] },
  DELL: { name: "Lidnap the Tortie Cat", ticker: "LIDNAP",
    blurb: "Lidnap, a small chocolate-and-red tortie with copper eyes, folds flat as a closed laptop lid on the warm potting-shed windowsill.",
    look: "A normal four-legged, small, short-haired tortoiseshell house cat: warm chocolate-brown fur mottled with soft red patches, and copper eyes. She lies folded flat on a warm windowsill. She wears nothing.",
    coat: ["#5A3A28", "#C0703A", "tortie", "#C77B30"] },
  QUBT: { blurb: "Prism, a sleek silver cat with small dark spots and ice-blue eyes, chases the rainbow dots a glass prism casts on the garden wall.",
    look: "A normal four-legged shorthair: a sleek silver cat dappled with small, round dark-grey spots, and ice-blue eyes. It wears nothing. It chases rainbow dots cast by a glass prism.",
    coat: ["#CDD2D9", "#474E59", "spotted", "#9FD3EA"] },
  PFIZER: { coat: ["#544A49", "#FDF3EA", "bicolor", "#C2A140"] },
  SHOP: { name: "Kiosk the Spotted Ginger Cat", ticker: "KIOSKPAW",
    blurb: "Kiosk, a plump ginger cat with rust-red spots and green-gold eyes, sits on the garden stall counter and bats the brass bell for each visitor.",
    look: "A normal four-legged, plump, short-haired house cat: warm ginger with round, darker rust-red spots on the body and legs, a paler cream belly, and green-gold eyes. It wears nothing. It sits on a garden stall counter beside a small brass bell.",
    coat: ["#DB8A45", "#9C4A1E", "spotted", "#A9B84A"] },
  AMBA: { blurb: "Vignette, a cream seal-point cat with a dark brown mask, ears, paws and tail, gazes out of the deep shade with wide sky-blue eyes." },
  GRND: { blurb: "Stripenose, a black tuxedo shorthair with a thin white nose stripe, white bib and olive-green eyes, greets every neighbour on the garden path." },
  BOEING: { blurb: "Windsock, a ginger tabby with a white chest, white paws and a striped orange tail, sits on the shed to watch which way the wind blows." },
  FLWS: { name: "Corsage the White Kitten", ticker: "CORSAGE",
    blurb: "Corsage, a round-faced white kitten with a thick, ruffled coat as crisp as fresh carnations, sits among pink and lavender blooms and purrs." },
  BROS: { name: "Jitter the Beanie Cat", ticker: "JITTERPAW",
    blurb: "Jitter, a scruffy black cat with big yellow eyes and a pink nose, wears a rust-orange knit beanie and grins at the first frosty autumn morning." },
  LUV: { name: "Paprika the Ruddy Kitten", ticker: "PAPRIKA",
    blurb: "Paprika, a ruddy-orange kitten with a softly ticked fluffy coat, tall ears and a cream chin, watches the garden sparrows." },
  WULF: { name: "Snug the Graphite Cat", ticker: "SNUGPAW",
    blurb: "Snug, a sleek graphite-grey shorthair with pale gold eyes, spends every afternoon stretched out on the warm air grate beside the potting shed." },
  CYPH: { name: "Drowse the Dark-Ruffed Cat", ticker: "DROWSEPAW",
    blurb: "Drowse, a big tawny longhair with a dark brown ruff and bright green eyes, sleeps through the busy afternoon and wakes for supper.",
    look: "A normal four-legged, big, long-haired house cat whose colouring is turned from the big-cat link: deep tawny fur, a thick darker brown ruff around the neck (the dark mane of the source art), a cream chin and bright green eyes. It wears nothing. The armour and its 'Z' mark in the source art are left out.",
    coat: ["#A26E3A", "#4A3222", "solid", "#5FB85A"] },
  BB: { name: "Curfew the Seal-Brown Cat", ticker: "CURFEWPAW",
    blurb: "Curfew, a sturdy seal-brown cat with a white bib, white socks and brass-gold eyes, walks the garden each night and checks every gate is shut.",
    look: "A big, sturdy, normal four-legged short-haired house cat: a dark seal-brown coat with a white bib, white chest and four white socks (a tuxedo pattern), and brass-gold eyes. He wears nothing: no collar, no logo, no emblem.",
    coat: ["#4A3527", "#F4EFE6", "tuxedo", "#C9A23A"] },
  IONQ: { name: "Icicle the Blue-Point Cat", ticker: "ICICLEPAW",
    blurb: "Icicle, an ice-white cat with slate-blue ears, mask, paws and tail and bright blue eyes, sits so still by the cold spring that moths land by him.",
    look: "A normal four-legged ice-white shorthair with blue-point markings: slate-blue ears, face mask, paws and tail, and bright blue eyes. He wears nothing and sits very still by a cold spring in the garden." },
  HIMS: { name: "Burly the Honey-and-White Cat",
    blurb: "Burly, a stocky, muscular honey-and-white shorthair with a broad white chest and white paws, meets the weekly delivery box at the gate.",
    look: "A normal four-legged, stocky, muscular shorthair house cat with a honey-orange and white coat: honey-orange back, head and tail, a broad white chest and white paws. Green eyes. Wears nothing." },
  LMT: { blurb: "Velvet, a sleek glossy-black shorthair whose coat shows faint darker rosettes in bright sun, watches the pond with round golden eyes." },
  POLYMARKET: { look: "A normal four-legged house cat that follows the kitten photo on the company's own market page 'First cat to $1b?'. The cat is a fluffy cream and pale-ginger cat with faint tabby stripes on the forehead, a paler muzzle and chin, a round face, and big copper eyes with dark pupils. It wears nothing." },
  SNDK: { look: "A normal four-legged house cat that follows the cats in the company's own ad. She has a fluffy white longhair coat with faint silver-grey tipping, most visible at the ear tips. Her face is flat and round, her ears are small, and her eyes have dark rims. She wears nothing. The red blanket she naps on is a prop from the ad scene, not clothing." },
  RIVN: { look: "A normal four-legged, slim, solid black shorthair with tall upright ears, long whiskers and gold-green eyes. It wears a light-aqua patterned collar with a small ring, as the source cat does." },
  AMC: { coat: ["#E3B04B", "#F6EFDF", "bicolor", "#D9A23A"], look: "A normal four-legged, fluffy, medium-longhair house cat. Cream-white with butter-yellow patches on the back and head, and honey-gold eyes. Wears nothing." },
  IBM: { look: "A normal four-legged house cat with a lean, long-legged build and a sandy-gold coat with round black spots, dark tear-marks running down from the eyes, a white-tipped tail and honey-gold eyes. It wears nothing." },
  AMD: { look: "An ordinary four-legged short-haired house cat in a small wild cat's coat: tawny-grey fur with dark brown spots, a naturally short bobbed tail like bobtail house-cat breeds, small tufts on its ear tips, a white chin and belly, and yellow-gold eyes. It wears nothing." },
  COPX: { name: "Rustle the Burnished Tabby",
    blurb: "Rustle, a burnished ginger tabby with dark rust-brown stripes and green eyes, pads through the tall grass and pounces on falling leaves.",
    look: "A burnished red-orange mackerel tabby with dark rust-brown stripes and green eyes. A normal four-legged shorthair house cat that wears nothing." },
  PTN: { blurb: "Umber, a sleek shorthair with a deep umber-brown coat that looks almost black in the shade and warm copper eyes, naps under the bay tree." },
  MRVL: { ticker: "COBBLEPAW" },
  DRAM: { name: "Pinrow the Glossy Cat" },
  DKNG: { name: "Rookie the Chestnut Cat", ticker: "ROOKIEPAW",
    blurb: "Rookie, a chestnut-brown shorthair with a thin white stripe down his chest and white toes, chases rolling acorns across the garden lawn." },
  SCHH: { name: "Rafter the Peach-Patch Cat", ticker: "RAFTERPAW",
    blurb: "Rafter, a slim grey tabby-and-white cat with green-gold eyes and a faint peach hip patch, naps along a beam of the garden pergola." },
  FLY: { blurb: "Pumice, a pale ash-grey shorthair flecked with darker grey, rolls in the dry garden path and leaves soft grey paw prints on every stone.",
    look: "A normal four-legged, short-haired house cat: pale ash-grey, the grey of moon dust (lunar soil), flecked all over with small, soft darker-grey speckles like pumice stone, and honey-gold eyes. It wears nothing. Its soft grey paw prints on the garden stones echo prints left in moon dust.",
    coat: ["#BDB8AF", "#8C867D", "spotted", "#D6A13F"] },
};
